In [1]:
import pandas as pd
data = pd.read_csv('c172_file_1.csv')
data

AltAGL   AltB  AltGPS  AltMSL  BaroA  E1_CHT1  E1_CHT2  E1_CHT3  \
0        0.0  855.8   745.7   833.6  30.05   231.88   224.27   243.57   
1        0.0  856.8   746.2   834.0  30.05   232.23   224.58   243.87   
2        0.0  855.8   746.4   834.2  30.05   232.59   224.84   244.12   
3        0.0  856.8   745.2   833.1  30.05   232.96   225.10   244.46   
4        0.0  856.8   745.2   833.0  30.05   233.30   225.36   244.75   
...      ...    ...     ...     ...    ...      ...      ...      ...   
5055     0.0  844.2   751.5   839.3  30.02   282.56   270.85   296.29   
5056     0.0  844.2   751.6   839.4  30.02   282.49   270.90   296.36   
5057     0.0  844.2   751.7   839.5  30.02   282.43   270.93   296.42   
5058     1.0  845.2   752.4   840.2  30.02   282.55   271.14   296.58   
5059     0.0  845.2   751.0   838.8  30.02   282.44   271.07   296.52   

      E1_CHT4  E1_EGT1  ...  LatAc  NormAc   OAT  Pitch  Roll  TAS   VSpd  \
0      245.74  1047.12  ...   0.01    0.01  27.2   1.25 -0.21  0.0 -14.35   
1      246.04  1046.06  ...   0.01   -0.00  27.2   1.23 -0.15  0.0   0.74   
2      246.34  1046.17  ...   0.00   -0.01  27.2   1.21 -0.14  0.0   5.96   
3      246.59  1046.32  ...  -0.00   -0.01  27.2   1.22 -0.14  0.0   9.95   
4      246.86  1043.91  ...   0.01   -0.01  27.2   1.22 -0.10  0.0  13.36   
...       ...      ...  ...    ...     ...   ...    ...   ...  ...    ...   
5055   288.37  1041.83  ...   0.00    0.04  26.0   1.45  0.00  0.0  15.17   
5056   288.45  1036.33  ...   0.00   -0.02  26.0   1.29  0.03  0.0  15.98   
5057   288.52  1030.14  ...   0.00    0.01  26.0   1.76  0.02  0.0  17.44   
5058   288.66  1024.47  ...  -0.00   -0.01  26.0   1.80  0.01  0.0  25.02   
5059   288.66  1022.10  ...  -0.00   -0.01  26.0   1.80  0.01  0.0  17.27   

      VSpdG  WndDr  WndSpd  
0      -3.9    0.0     0.0  
1      -3.9    0.0     0.0  
2      -3.9    0.0     0.0  
3      -3.9    0.0     0.0  
4      -3.9    0.0     0.0  
...     ...    ...     ...  
5055   -3.9    0.0     0.0  
5056    0.0    0.0     0.0  
5057    0.0    0.0     0.0  
5058    0.0    0.0     0.0  
5059    0.0    0.0     0.0  

[5060 rows x 31 columns]

In [21]:
%run real_demo.py

avg: tensor([[0.1341]], dtype=torch.float64, grad_fn=<SplitBackward>)
logvar: tensor([[-0.1048]], dtype=torch.float64, grad_fn=<SplitBackward>)


NameError: name 'AffineHalfFlow' is not defined

In [ ]:
%run real_demo_2.py

tensor([[1.4457, 1.7993]])
tensor([[-0.2512,  1.5122]])
tensor([[ 0.1094, -0.1909]])
tensor([[-0.0054, -0.5114]])
tensor([[-1.4970,  0.2727]])
tensor([[0.0429, 0.1487]])
tensor([[-1.2389,  0.5972]])
tensor([[-0.8779,  1.0557]])
tensor([[ 1.9234, -0.7432]])
tensor([[0.7153, 3.1107]])
tensor([[-0.7609, -0.6671]])
tensor([[0.8247, 0.4270]])
tensor([[ 0.2170, -0.0091]])
tensor([[ 0.5738, -1.0065]])
tensor([[ 0.0112, -0.7484]])
tensor([[0.3641, 0.4768]])
tensor([[ 0.2881, -0.4137]])
tensor([[-2.5289,  0.4870]])
tensor([[0.3464, 0.0374]])
tensor([[-0.4974,  0.1217]])
tensor([[-0.3079, -1.5233]])
tensor([[-1.1430, -0.9726]])
tensor([[0.9221, 0.1895]])
tensor([[-0.1380,  1.7054]])
tensor([[ 1.5842, -1.5386]])
tensor([[0.6247, 0.8178]])
tensor([[-0.3730, -1.6803]])
tensor([[-0.6230, -0.8621]])
tensor([[-0.9479,  0.7840]])
tensor([[-2.3399,  0.2344]])
tensor([[0.6969, 0.5534]])
tensor([[-0.1864, -1.2936]])
tensor([[ 0.0593, -0.3393]])
tensor([[0.4480, 0.4078]])
tensor([[ 0.3624, -0.9147]])
tenso

C:\Users\Charlie\anaconda3\lib\site-packages\torch\nn\_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


tensor([[-0.1749, -0.8355]])
tensor([[-0.6021,  1.2450]])
tensor([[-0.0221, -2.6655]])
tensor([[1.5551, 0.0910]])
tensor([[-2.1966, -0.4988]])
tensor([[-0.7934,  0.6053]])
tensor([[-0.1002, -0.0896]])
tensor([[0.9727, 1.2559]])
tensor([[-2.2438, -0.6357]])
tensor([[-2.3592, -0.8270]])
tensor([[2.0301, 0.8886]])
tensor([[ 0.0068, -1.2867]])
tensor([[-1.3929, -0.8835]])
tensor([[ 1.2974, -0.5407]])
tensor([[1.1686, 0.9439]])
tensor([[-0.9175,  0.3715]])
tensor([[-1.8412,  1.2818]])
tensor([[-2.0311,  0.5983]])
tensor([[1.1182, 0.0762]])
tensor([[1.3944, 1.3244]])
tensor([[ 0.7240, -0.6065]])
tensor([[-2.3247, -0.7601]])
tensor([[ 0.4760, -0.2503]])
tensor([[-0.5007,  0.1506]])
tensor([[ 0.6170, -0.8043]])
tensor([[-0.4076,  0.4900]])
tensor([[-0.0073,  0.6315]])
tensor([[-1.0910, -1.3122]])
tensor([[ 1.6310, -1.5346]])
tensor([[0.4938, 0.4468]])
tensor([[-1.8867, -0.8975]])
tensor([[-1.1651,  0.9057]])
tensor([[ 0.0116, -1.0537]])
tensor([[-0.3659, -1.7048]])
tensor([[-0.4050,  1.6148]])

tensor([[-0.5937,  0.7584]])
tensor([[0.8612, 0.5646]])
tensor([[ 1.6741, -0.2228]])
tensor([[1.6335, 0.7471]])
tensor([[0.7891, 0.9053]])
tensor([[ 0.1638, -0.9030]])
tensor([[-1.6980,  2.4467]])
tensor([[-0.3274, -1.9683]])
tensor([[1.1811, 0.9199]])
tensor([[ 0.3752, -1.8640]])
tensor([[ 0.1890, -0.4431]])
tensor([[-0.7107, -1.1131]])
tensor([[1.0354, 0.4211]])
tensor([[0.1148, 0.1216]])
tensor([[0.8429, 1.7143]])
tensor([[ 0.6537, -0.3113]])
tensor([[-0.3311,  1.1860]])
tensor([[-0.8835,  0.6692]])
tensor([[ 0.3762, -0.9206]])
tensor([[-1.6345,  0.6989]])
tensor([[-0.8905, -1.0687]])
tensor([[-2.1127, -0.0861]])
tensor([[-0.3836, -0.1790]])
tensor([[0.0086, 1.9152]])
tensor([[-1.7328, -0.1104]])
tensor([[0.8781, 0.6505]])
tensor([[0.9329, 0.3471]])
tensor([[-0.1637, -0.2749]])
tensor([[ 0.0003, -0.0944]])
tensor([[1.6918, 0.2432]])
tensor([[0.2248, 1.8264]])
tensor([[-1.6585, -0.3711]])
tensor([[-0.6161,  1.3669]])
tensor([[-1.9311, -0.0052]])
tensor([[-0.0428, -0.1475]])
tensor([[

tensor([[ 1.6996, -1.4948]])
tensor([[-0.9383,  0.1126]])
tensor([[0.4227, 0.5935]])
Epoch[1/10] Loss: 0.168
tensor([[-0.6243,  1.4454]])
tensor([[0.6568, 0.4948]])
tensor([[-0.3783,  0.1958]])
tensor([[ 0.0565, -0.3769]])
tensor([[-0.1612, -0.4128]])
tensor([[0.6037, 1.0472]])
tensor([[-0.5512, -1.0609]])
tensor([[ 0.6396, -0.6186]])
tensor([[ 1.0648, -0.6254]])
tensor([[ 0.8606, -0.5672]])
tensor([[-1.0146, -0.7285]])
tensor([[ 1.1165, -0.0479]])
tensor([[ 2.3046, -1.9339]])
tensor([[0.3392, 0.9879]])
tensor([[-0.0754,  0.5926]])
tensor([[-1.1070, -0.7602]])
tensor([[0.0084, 1.6206]])
tensor([[-1.1466, -0.4570]])
tensor([[ 0.0366, -1.1049]])
tensor([[ 0.0375, -0.9366]])
tensor([[-0.0933, -0.3913]])
tensor([[0.5618, 0.6806]])
tensor([[-0.1134,  1.1932]])
tensor([[ 2.2592, -0.0099]])
tensor([[0.0209, 0.6301]])
tensor([[-2.0606, -0.5708]])
tensor([[-0.2689,  1.7776]])
tensor([[-0.8427,  0.4653]])
tensor([[ 1.2262, -1.5854]])
tensor([[ 0.8405, -0.2832]])
tensor([[0.7664, 0.5916]])
tensor

tensor([[-0.4165,  0.3602]])
tensor([[0.3117, 1.8903]])
tensor([[-0.7286, -1.2965]])
tensor([[ 0.4028, -1.0152]])
tensor([[-0.4444,  0.0432]])
tensor([[ 0.0444, -1.6534]])
tensor([[0.4300, 0.4343]])
tensor([[-0.6364,  0.5956]])
tensor([[-2.3674,  1.9046]])
tensor([[0.0255, 0.5585]])
tensor([[ 0.0529, -0.3644]])
tensor([[ 0.2256, -0.4936]])
tensor([[ 0.7762, -0.0657]])
tensor([[-0.1434,  0.2948]])
tensor([[-0.5140,  1.3740]])
tensor([[-0.0880,  1.0576]])
tensor([[-1.0005, -2.0495]])
tensor([[1.5363, 0.0585]])
tensor([[ 0.6286, -0.5070]])
tensor([[-0.1570,  0.5946]])
tensor([[0.6694, 0.3265]])
tensor([[1.5449, 0.9547]])
tensor([[-0.0290, -0.7184]])
tensor([[ 1.5463, -1.3739]])
tensor([[-0.6346, -0.3048]])
tensor([[ 0.8986, -0.6707]])
tensor([[1.9586, 0.7982]])
tensor([[-0.7943,  0.4250]])
tensor([[-1.1236,  0.2400]])
tensor([[1.5964, 0.6253]])
tensor([[-2.5269, -1.8383]])
tensor([[-0.3636, -0.1252]])
tensor([[-0.0137,  0.3805]])
tensor([[-1.4646,  0.8904]])
tensor([[ 2.0955, -0.0146]])
t

tensor([[-0.2369,  0.5116]])
tensor([[ 0.8126, -1.8966]])
tensor([[-0.1430,  1.1667]])
tensor([[-0.5418,  0.0232]])
tensor([[-0.6973,  0.0595]])
tensor([[ 0.9700, -2.3958]])
tensor([[-1.1896,  0.8952]])
tensor([[-0.1821, -0.4329]])
tensor([[ 0.6341, -0.9987]])
tensor([[0.6836, 1.0525]])
tensor([[-1.2268, -0.1355]])
tensor([[ 0.8011, -1.2637]])
tensor([[ 0.2474, -0.8494]])
tensor([[0.2235, 0.1335]])
tensor([[0.4404, 1.2921]])
tensor([[-2.7110,  0.2507]])
tensor([[ 0.5242, -0.2628]])
tensor([[-1.9440, -0.2945]])
tensor([[0.6933, 1.9292]])
tensor([[0.5683, 1.0600]])
tensor([[1.3446, 0.8425]])
tensor([[-0.0364,  2.0633]])
tensor([[-0.0767,  0.8018]])
tensor([[-1.2024,  0.9507]])
tensor([[-0.8793, -1.1478]])
tensor([[1.0624, 0.6352]])
tensor([[ 0.2611, -0.0379]])
tensor([[1.2954, 1.9674]])
tensor([[-1.9097, -0.9191]])
tensor([[ 0.6087, -0.8050]])
tensor([[-0.3279, -0.1118]])
tensor([[-0.3155, -0.5718]])
tensor([[0.2680, 0.3292]])
tensor([[ 1.6785, -0.7871]])
tensor([[-1.4293,  1.7709]])
ten

tensor([[0.6308, 0.1611]])
tensor([[ 0.1974, -1.5884]])
tensor([[-0.8368,  0.6771]])
tensor([[0.7690, 0.6611]])
tensor([[ 1.7465, -0.1571]])
tensor([[ 1.2417, -0.8236]])
tensor([[-0.1997, -0.5929]])
tensor([[0.0321, 1.1513]])
tensor([[-0.7373,  0.9074]])
tensor([[0.5834, 1.6537]])
tensor([[-0.6582,  1.3258]])
tensor([[-0.3347, -1.0087]])
tensor([[ 0.3910, -1.6205]])
tensor([[1.1195, 1.1336]])
tensor([[ 1.4151, -1.9313]])
tensor([[-0.8854,  0.6104]])
tensor([[1.2119, 0.5749]])
tensor([[-0.0168, -0.3611]])
tensor([[0.1631, 0.0155]])
tensor([[ 0.5052, -1.0842]])
tensor([[-0.7840,  1.3484]])
tensor([[0.1256, 0.2858]])
tensor([[-0.0299,  0.3136]])
tensor([[ 0.3127, -0.0862]])
tensor([[1.0442, 0.7221]])
tensor([[-1.1104,  0.3792]])
tensor([[0.2899, 0.4892]])
tensor([[ 0.7812, -1.1764]])
tensor([[1.4650, 0.8139]])
tensor([[-0.7651, -0.8030]])
tensor([[0.3254, 1.0823]])
tensor([[ 0.9006, -0.1878]])
tensor([[0.7378, 1.5209]])
tensor([[0.0247, 0.3247]])
tensor([[1.5795, 0.8720]])
tensor([[ 2.237

tensor([[ 1.9516, -0.8047]])
tensor([[-0.9702,  1.2827]])
tensor([[-0.2599, -0.4379]])
tensor([[ 1.0842, -0.2759]])
tensor([[1.7512, 0.1061]])
tensor([[ 1.9584, -1.1001]])
tensor([[-0.9961, -0.7766]])
tensor([[-0.2637, -0.2364]])
tensor([[-0.2928,  0.7508]])
tensor([[ 0.2355, -1.0692]])
tensor([[-0.2667,  0.6729]])
tensor([[-0.5306,  0.2292]])
tensor([[0.5830, 0.4216]])
tensor([[ 0.3167, -0.6379]])
tensor([[0.6760, 0.5775]])
tensor([[0.6393, 0.7578]])
tensor([[-0.7902, -0.5252]])
tensor([[-1.5620, -0.3343]])
tensor([[ 0.0629, -0.1840]])
tensor([[-1.2161, -1.3046]])
tensor([[0.3020, 0.0286]])
tensor([[0.2040, 0.9663]])
tensor([[-1.0866, -1.6749]])
tensor([[-1.7218,  0.4490]])
tensor([[0.2443, 0.3994]])
tensor([[0.3495, 0.6040]])
tensor([[ 0.6271, -0.1430]])
tensor([[-0.4580,  0.3920]])
tensor([[-1.7690, -0.7181]])
tensor([[0.7276, 0.3490]])
tensor([[-0.0830, -0.2061]])
tensor([[ 1.3626, -1.3523]])
tensor([[ 0.3890, -0.0353]])
tensor([[-0.9170, -0.6566]])
tensor([[2.1579, 0.7325]])
tenso

tensor([[ 0.4134, -1.5714]])
tensor([[-0.4718,  0.3607]])
tensor([[-1.4915, -0.0298]])
tensor([[-1.0213,  1.0008]])
tensor([[-0.6368, -1.8294]])
tensor([[-0.5138, -0.7950]])
tensor([[-0.3161,  0.7687]])
tensor([[-0.9692,  1.2315]])
tensor([[-0.2816,  0.2375]])
tensor([[1.5702, 0.0291]])
tensor([[1.4593, 1.4105]])
tensor([[ 0.3554, -0.8329]])
tensor([[-0.6259,  0.6651]])
tensor([[0.0433, 1.6679]])
tensor([[0.5993, 1.5196]])
tensor([[-1.3191, -1.6141]])
tensor([[ 0.4767, -0.3667]])
tensor([[-0.2006, -0.2340]])
tensor([[-0.1683,  0.5928]])
tensor([[ 1.7728, -0.1386]])
tensor([[-1.2304,  0.6792]])
tensor([[-2.3267,  0.5170]])
tensor([[1.2512, 0.3282]])
tensor([[-0.8504,  0.5616]])
tensor([[0.7523, 1.0956]])
tensor([[1.2237, 0.7560]])
tensor([[-0.2332,  0.4045]])
tensor([[ 0.1139, -0.8000]])
tensor([[-0.8116,  1.4147]])
tensor([[-1.1426,  0.3446]])
tensor([[-0.9583, -1.4547]])
tensor([[0.2834, 0.7971]])
tensor([[0.3409, 0.2698]])
tensor([[ 0.4806, -0.4632]])
tensor([[-0.3161,  0.1903]])
ten

tensor([[1.8875, 0.0324]])
tensor([[ 0.1084, -1.7686]])
tensor([[ 1.5786, -0.8488]])
tensor([[-1.5503, -0.7282]])
tensor([[0.9085, 0.3441]])
tensor([[-0.5083, -2.0981]])
tensor([[0.2999, 0.9290]])
tensor([[-0.9321, -1.1582]])
tensor([[-0.7886, -0.1408]])
tensor([[ 0.9656, -1.3642]])
tensor([[0.8940, 0.3337]])
tensor([[0.2349, 0.5438]])
tensor([[-0.7485,  0.4487]])
tensor([[ 1.2752, -0.7113]])
tensor([[-0.9735,  0.5068]])
tensor([[0.5387, 0.2447]])
tensor([[-1.3313, -1.0864]])
tensor([[-0.3730,  0.1809]])
tensor([[0.5154, 0.0266]])
tensor([[-1.1068,  1.1524]])
tensor([[ 0.9362, -0.3027]])
tensor([[ 0.2875, -0.1257]])
tensor([[-0.3065, -0.2974]])
tensor([[-0.3875,  0.1042]])
tensor([[ 0.0582, -0.0909]])
tensor([[-0.2894,  0.3357]])
tensor([[ 0.4054, -0.9397]])
tensor([[-1.1130,  1.2820]])
tensor([[ 0.1307, -1.3367]])
tensor([[ 1.0684, -1.7390]])
tensor([[0.6312, 1.3627]])
tensor([[-0.2964,  0.3590]])
tensor([[ 0.5626, -0.0192]])
tensor([[-1.1787, -0.5976]])
tensor([[ 0.0336, -0.9450]])
t

tensor([[-1.2169,  0.4827]])
tensor([[-0.2367,  0.9171]])
tensor([[-0.0774, -0.6878]])
tensor([[-0.3822, -0.1880]])
tensor([[-0.0885, -2.1929]])
tensor([[ 0.5682, -0.8539]])
tensor([[-0.5322, -0.0247]])
tensor([[-0.7561,  0.3580]])
tensor([[ 0.8465, -1.1322]])
tensor([[-1.6884,  0.3580]])
tensor([[ 0.2018, -1.3037]])
tensor([[ 0.6868, -0.3808]])
tensor([[-0.3712,  0.2114]])
tensor([[0.6676, 0.8168]])
tensor([[-0.9780,  0.0129]])
tensor([[-0.3450, -0.9792]])
tensor([[-1.5838,  2.2502]])
tensor([[ 0.8561, -1.1909]])
tensor([[-0.4288, -0.1478]])
tensor([[ 1.1503, -0.4204]])
tensor([[ 2.0294, -1.4286]])
tensor([[-0.2895, -0.1066]])
tensor([[ 0.4019, -2.0023]])
Epoch[3/10] Loss: 0.165
tensor([[-0.9109,  0.5600]])
tensor([[0.4449, 1.0218]])
tensor([[0.5364, 1.1569]])
tensor([[0.3676, 1.5446]])
tensor([[-1.2540, -0.5604]])
tensor([[-0.8040, -0.2052]])
tensor([[ 1.2544, -0.9083]])
tensor([[-0.8991, -0.2943]])
tensor([[-0.2666,  0.7075]])
tensor([[-0.8038, -0.3383]])
tensor([[1.1024, 1.1521]])


tensor([[-1.1101,  1.4199]])
tensor([[0.7374, 0.7016]])
tensor([[-0.8717, -0.0922]])
tensor([[-0.3799,  1.2946]])
tensor([[-0.9689, -0.8472]])
tensor([[1.6794, 0.3730]])
tensor([[-0.5558,  1.9226]])
tensor([[-0.6362, -0.0763]])
tensor([[0.8730, 0.5657]])
tensor([[-0.6363, -1.0906]])
tensor([[ 0.0979, -1.4201]])
tensor([[-0.5762,  0.0693]])
tensor([[0.7742, 0.3297]])
tensor([[0.9957, 0.6556]])
tensor([[ 0.0015, -0.3514]])
tensor([[-0.3048,  0.9142]])
Epoch[3/10] Loss: 0.137
tensor([[-1.7608,  1.5741]])
tensor([[-1.3029,  1.0358]])
tensor([[-0.5404, -1.1086]])
tensor([[0.1399, 1.1033]])
tensor([[0.8729, 1.1451]])
tensor([[-0.3950, -0.7023]])
tensor([[-1.3473,  0.2085]])
tensor([[-1.4383,  0.3396]])
tensor([[-0.3843, -0.5990]])
tensor([[-1.8683, -0.4043]])
tensor([[-0.6186, -0.0420]])
tensor([[ 0.8280, -0.0011]])
tensor([[0.6841, 0.7613]])
tensor([[-2.7999e-01,  2.8294e-05]])
tensor([[-0.3979, -0.2949]])
tensor([[ 0.4032, -0.3045]])
tensor([[-1.1050,  0.3483]])
tensor([[-0.8959, -0.1442]]

tensor([[1.6743, 0.4506]])
tensor([[ 0.9651, -1.3967]])
tensor([[ 0.0659, -1.4148]])
Epoch[3/10] Loss: 0.133
tensor([[-0.7805, -0.3871]])
tensor([[-1.6835,  0.4648]])
tensor([[ 0.5977, -0.7026]])
tensor([[-1.5104,  1.8526]])
tensor([[ 0.7588, -1.1393]])
tensor([[-0.4958,  0.4460]])
tensor([[-0.3946,  0.0343]])
tensor([[-2.2968,  0.7831]])
tensor([[1.5221, 1.2810]])
tensor([[-0.6169, -0.1150]])
tensor([[-0.8280,  0.4186]])
tensor([[0.1939, 0.2964]])
tensor([[0.3725, 0.1263]])
tensor([[-0.0664, -0.7243]])
tensor([[ 0.9310, -1.0797]])
tensor([[0.1302, 0.1700]])
tensor([[0.1603, 0.3156]])
tensor([[ 0.0313, -0.0628]])
tensor([[-1.4437, -1.1237]])
tensor([[-2.3339, -1.4477]])
tensor([[-0.5366,  0.4190]])
tensor([[0.4532, 1.0765]])
tensor([[0.1146, 1.4399]])
tensor([[-1.4223, -0.2929]])
tensor([[ 0.6170, -1.6154]])
tensor([[-0.0076, -0.7259]])
tensor([[-0.7152,  0.0299]])
tensor([[-0.2498, -0.3385]])
tensor([[-1.0434, -1.3860]])
tensor([[-0.3319,  0.0915]])
tensor([[0.6409, 0.4961]])
tensor([

tensor([[0.3965, 0.2709]])
tensor([[ 0.9918, -1.8706]])
tensor([[0.8799, 2.2357]])
tensor([[-0.5556,  0.0774]])
tensor([[ 0.4193, -0.4433]])
tensor([[ 0.7812, -0.0745]])
tensor([[-1.4150, -0.8419]])
tensor([[ 1.0330, -0.9801]])
tensor([[0.7249, 1.4233]])
tensor([[ 1.7352, -0.6836]])
tensor([[0.3836, 1.6387]])
tensor([[ 0.3544, -2.6623]])
tensor([[ 0.2163, -0.8227]])
tensor([[ 0.7293, -0.9672]])
tensor([[0.8628, 1.4836]])
tensor([[0.8154, 1.5850]])
tensor([[-1.0500, -1.6512]])
tensor([[-0.6070, -0.6416]])
tensor([[ 1.0497, -0.9585]])
tensor([[0.8113, 0.5056]])
tensor([[1.0269, 0.9976]])
tensor([[0.5118, 2.7043]])
tensor([[ 1.1159, -0.6075]])
tensor([[-0.7531,  1.3590]])
tensor([[1.5717, 0.9886]])
tensor([[1.6571, 0.1980]])
tensor([[0.3063, 0.7964]])
tensor([[1.0221, 0.2893]])
Epoch[4/10] Loss: 0.131
tensor([[1.5272, 0.0765]])
tensor([[2.9150, 0.3806]])
tensor([[-1.2921,  0.1281]])
tensor([[-1.2460, -2.1757]])
tensor([[ 2.0751, -0.0061]])
tensor([[-0.3043, -0.2318]])
tensor([[-0.0061,  0

tensor([[ 0.1570, -0.0654]])
tensor([[ 1.4585, -0.4578]])
tensor([[ 2.1082, -0.0695]])
tensor([[-0.7529, -1.5721]])
tensor([[0.1338, 2.0102]])
tensor([[-1.8350, -0.4369]])
tensor([[0.3714, 0.0356]])
tensor([[ 1.5303, -1.6030]])
tensor([[ 0.3225, -0.9077]])
tensor([[-1.2994, -0.6964]])
tensor([[ 0.4685, -0.6052]])
tensor([[-0.3578, -1.0656]])
tensor([[ 0.1152, -0.1790]])
Epoch[4/10] Loss: 0.169
tensor([[0.0443, 0.1699]])
tensor([[-2.1318,  0.3861]])
tensor([[-0.4080,  0.0905]])
tensor([[ 0.2515, -0.9359]])
tensor([[ 1.5055, -0.6819]])
tensor([[0.7348, 0.1653]])
tensor([[0.4831, 0.0934]])
tensor([[ 0.2253, -0.6010]])
tensor([[0.7219, 0.0805]])
tensor([[ 0.3963, -0.1376]])
tensor([[-0.4134, -0.8699]])
tensor([[1.1179, 1.4777]])
tensor([[-0.4095, -0.9608]])
tensor([[-0.8503,  0.2398]])
tensor([[-0.0629, -1.2562]])
tensor([[-0.7058, -0.4588]])
tensor([[ 1.2405, -0.8352]])
tensor([[ 0.7985, -0.1179]])
tensor([[-0.2676,  2.2341]])
tensor([[-0.4458, -1.0740]])
tensor([[-0.4201, -0.2432]])
tens

tensor([[ 0.9888, -1.2929]])
tensor([[0.6407, 0.2541]])
tensor([[-1.1176, -0.0408]])
tensor([[0.2634, 0.0852]])
tensor([[ 1.6274, -0.5858]])
tensor([[-1.3705,  0.1761]])
Epoch[4/10] Loss: 0.157
tensor([[1.1477, 0.7408]])
tensor([[-0.1591,  1.7914]])
tensor([[-1.6812,  0.3008]])
tensor([[1.1466, 0.4108]])
tensor([[ 2.6975, -0.8947]])
tensor([[ 0.6897, -0.2561]])
tensor([[0.6562, 0.6419]])
tensor([[ 1.4006, -0.3115]])
tensor([[ 0.7795, -1.2061]])
tensor([[ 0.6038, -0.2717]])
tensor([[-0.2644,  0.2950]])
tensor([[-0.5554, -1.1895]])
tensor([[ 0.9966, -0.3241]])
tensor([[ 0.5599, -0.0117]])
tensor([[ 2.1418, -0.4189]])
tensor([[ 0.0206, -0.1391]])
tensor([[ 1.1060, -1.9749]])
tensor([[-0.0315,  1.3500]])
tensor([[ 1.3882, -0.2685]])
tensor([[0.0865, 1.1313]])
tensor([[0.1160, 1.0709]])
tensor([[1.7336, 0.5574]])
tensor([[-0.7764,  0.2691]])
tensor([[ 0.3653, -1.0001]])
tensor([[-0.7281,  0.9456]])
tensor([[ 0.1956, -1.7139]])
tensor([[0.0536, 0.6523]])
tensor([[0.0391, 0.7944]])
tensor([[ 

tensor([[ 0.3271, -0.5160]])
tensor([[ 0.8784, -0.0672]])
tensor([[-1.1062,  1.7862]])
tensor([[-0.1370,  1.7958]])
tensor([[0.3589, 2.0595]])
tensor([[-0.2940,  1.3267]])
tensor([[1.2092, 1.8048]])
tensor([[-3.1484, -0.4366]])
tensor([[0.3120, 0.0629]])
tensor([[ 0.0300, -0.3432]])
tensor([[ 0.7174, -0.6257]])
tensor([[ 0.8150, -0.3522]])
tensor([[ 0.7527, -0.4400]])
tensor([[0.6504, 0.1758]])
tensor([[-2.1493e+00,  4.2593e-04]])
tensor([[-0.7855, -0.3026]])
tensor([[-0.3343, -0.8708]])
tensor([[1.1165, 0.3237]])
tensor([[-1.2316,  1.3189]])
tensor([[-1.9019, -1.6492]])
tensor([[0.3429, 0.4926]])
tensor([[0.1099, 0.4890]])
tensor([[0.7317, 0.3119]])
tensor([[-0.0441,  0.0968]])
tensor([[0.6204, 1.4214]])
tensor([[-0.4412, -0.4679]])
tensor([[ 0.5519, -1.3435]])
tensor([[-1.2476,  2.3577]])
tensor([[0.0632, 0.4910]])
tensor([[-0.3153,  0.6844]])
tensor([[-0.7414, -0.1613]])
tensor([[-2.2626, -0.4006]])
tensor([[-1.0974,  0.1641]])
tensor([[-0.2010,  0.7813]])
tensor([[-0.3139, -0.8932]

tensor([[-2.4275, -0.4839]])
tensor([[-0.8831,  0.7527]])
tensor([[-0.1008, -2.3116]])
tensor([[ 0.9381, -0.0622]])
tensor([[ 0.1403, -0.1235]])
tensor([[-0.9202,  0.1976]])
tensor([[-0.8054, -0.5645]])
tensor([[-0.4320, -1.1729]])
tensor([[-0.2730, -0.0049]])
tensor([[-0.9743,  0.3592]])
tensor([[-1.7134,  0.5643]])
tensor([[1.3786, 0.1934]])
tensor([[0.8362, 2.1118]])
tensor([[-0.3912,  0.0074]])
tensor([[-0.8371, -0.6636]])
tensor([[-1.2797,  1.0456]])
tensor([[ 0.4032, -1.9496]])
tensor([[-0.4431, -0.4617]])
tensor([[-1.2939,  1.1922]])
tensor([[ 0.6606, -0.1445]])
tensor([[-0.4471, -2.2319]])
tensor([[0.6183, 1.9442]])
tensor([[1.9153, 0.5083]])
tensor([[-0.7742, -1.9624]])
tensor([[ 0.4821, -0.9677]])
tensor([[-1.1486,  0.2976]])
tensor([[-1.0871, -0.2790]])
tensor([[0.8309, 0.4891]])
tensor([[ 0.1240, -0.1260]])
tensor([[-0.4787,  0.7756]])
tensor([[-1.6982, -0.0034]])
tensor([[-0.5951, -1.3360]])
tensor([[-1.1947, -1.9044]])
tensor([[0.2345, 0.1311]])
tensor([[-0.5959, -1.4337]

tensor([[-1.6032,  0.3259]])
tensor([[0.3227, 1.1364]])
tensor([[-1.1259, -0.6399]])
tensor([[ 0.0749, -1.6586]])
tensor([[ 0.1135, -1.0175]])
tensor([[-1.3437,  1.5017]])
tensor([[-0.5159,  0.2820]])
tensor([[2.1923, 0.5258]])
tensor([[-2.1871, -1.0150]])
tensor([[0.9857, 0.2610]])
tensor([[ 1.4778, -1.2032]])
tensor([[ 0.2717, -0.5771]])
tensor([[-0.3769, -1.2056]])
tensor([[-0.0945, -2.1053]])
tensor([[ 0.2115, -0.1864]])
tensor([[ 0.3520, -0.3907]])
tensor([[ 0.3157, -0.6681]])
tensor([[1.6802, 0.3167]])
tensor([[-0.1343, -0.0379]])
tensor([[0.6716, 2.2489]])
tensor([[-0.7732, -1.4043]])
tensor([[ 0.0371, -0.3551]])
tensor([[ 0.5671, -0.6876]])
tensor([[0.7810, 0.8809]])
tensor([[ 0.6183, -1.6809]])
tensor([[-1.0177, -0.2891]])
tensor([[-0.2252,  1.3927]])
tensor([[-1.1269, -0.1348]])
tensor([[-0.0792,  1.0123]])
tensor([[0.7689, 2.3668]])
tensor([[ 0.3517, -0.6326]])
tensor([[ 0.6472, -1.0238]])
tensor([[ 1.3592, -0.3914]])
tensor([[-1.9958, -0.3957]])
tensor([[-1.0406, -2.1260]])

tensor([[-1.9707, -0.9303]])
tensor([[-1.0772,  1.1941]])
tensor([[-0.2062, -0.3938]])
tensor([[ 0.3032, -0.3912]])
tensor([[-2.1450,  0.9245]])
tensor([[-1.6027,  1.3956]])
tensor([[-1.1623,  1.6797]])
tensor([[ 1.0706, -1.0663]])
tensor([[ 0.3499, -0.3152]])
tensor([[-0.8224,  1.5416]])
tensor([[ 0.1831, -0.1185]])
tensor([[ 0.1651, -0.2747]])
tensor([[-0.1781, -0.1817]])
tensor([[-0.3050,  0.5321]])
tensor([[-0.4391, -1.6319]])
tensor([[-1.3209,  0.1559]])
tensor([[0.1028, 1.0213]])
tensor([[0.8135, 0.7759]])
tensor([[ 1.1880, -0.3063]])
tensor([[2.1456, 0.5647]])
tensor([[ 1.1491, -0.2873]])
tensor([[-0.0126, -1.1061]])
tensor([[-2.4820,  0.5724]])
tensor([[1.3990, 0.3316]])
tensor([[ 1.8231, -0.0079]])
tensor([[1.5030, 0.3098]])
tensor([[0.9684, 1.0426]])
tensor([[ 0.2010, -0.4046]])
tensor([[0.3421, 0.0832]])
tensor([[-0.6615,  0.9600]])
tensor([[1.5031, 1.3186]])
tensor([[-0.3719,  0.8403]])
tensor([[ 0.5380, -0.2460]])
tensor([[-0.2852,  0.1125]])
tensor([[-1.3216,  1.0895]])
t

tensor([[-0.6472, -0.2155]])
tensor([[-0.3096, -0.9251]])
tensor([[-1.5403, -0.1882]])
tensor([[-0.2238,  1.3862]])
tensor([[-0.4561,  0.6294]])
tensor([[-1.1098,  0.3605]])
tensor([[-0.5240,  0.4419]])
tensor([[-0.9279,  0.5111]])
tensor([[-1.7195, -2.2293]])
tensor([[-0.2204, -0.3226]])
tensor([[-0.9153,  1.4671]])
tensor([[ 1.5461, -0.5433]])
tensor([[0.3540, 0.1943]])
tensor([[0.7414, 1.7686]])
tensor([[1.7812, 0.9145]])
tensor([[-0.2196,  0.1931]])
tensor([[ 0.8202, -1.3779]])
tensor([[ 0.0519, -1.2041]])
tensor([[ 0.6133, -0.9441]])
tensor([[ 0.2820, -1.7249]])
tensor([[ 0.2836, -0.8998]])
tensor([[-1.2063,  1.2554]])
tensor([[1.0953, 0.9909]])
tensor([[-0.3568,  0.0781]])
tensor([[ 0.3884, -0.4544]])
tensor([[ 0.0673, -0.4711]])
tensor([[-0.3101, -0.4628]])
tensor([[-0.2689, -0.1496]])
tensor([[0.9061, 0.0979]])
tensor([[-0.1705,  0.2666]])
tensor([[ 2.1665, -0.6733]])
tensor([[0.3587, 0.2499]])
tensor([[-1.2290,  1.4217]])
Epoch[5/10] Loss: 0.142
tensor([[-0.3241,  0.0174]])
te

tensor([[ 0.3301, -1.4849]])
tensor([[-0.4986,  0.4982]])
tensor([[1.9492, 0.2910]])
tensor([[-0.1221,  1.0840]])
tensor([[ 0.0683, -1.0095]])
tensor([[-0.2849,  0.4872]])
tensor([[-0.8386, -0.3728]])
tensor([[-1.2417,  0.3528]])
tensor([[-1.5435, -0.7971]])
tensor([[1.5871, 0.6055]])
tensor([[-1.2914, -1.3080]])
tensor([[0.4588, 0.5898]])
tensor([[-0.0332, -0.1373]])
tensor([[-0.9117, -2.7560]])
tensor([[ 0.3396, -1.0747]])
tensor([[ 1.5137, -0.4911]])
tensor([[0.4602, 0.4744]])
tensor([[-1.6083,  0.3688]])
tensor([[-0.6022,  0.2321]])
tensor([[0.2130, 0.6736]])
tensor([[-0.2588, -0.0690]])
tensor([[0.9214, 1.4129]])
tensor([[ 0.4834, -0.4495]])
tensor([[-1.3867,  0.2164]])
tensor([[ 0.1347, -0.7267]])
tensor([[ 1.6628, -0.6117]])
tensor([[0.6762, 0.9492]])
tensor([[-0.5564,  1.0998]])
tensor([[-0.0950,  0.1880]])
tensor([[ 1.3322, -1.4744]])
tensor([[0.4387, 0.0121]])
tensor([[0.7236, 0.1095]])
tensor([[-0.3257, -0.0188]])
tensor([[-0.0928,  0.6663]])
tensor([[ 0.8428, -0.2018]])
ten

tensor([[1.3777, 1.4344]])
tensor([[ 0.7068, -1.0400]])
tensor([[-0.7150, -1.1298]])
tensor([[ 1.6633, -0.1781]])
tensor([[-1.0206,  0.2439]])
tensor([[-1.2584, -0.3337]])
tensor([[-1.1944,  0.0591]])
tensor([[0.9992, 1.2913]])
tensor([[-1.0189,  1.2312]])
tensor([[-0.9895, -0.3318]])
tensor([[0.7022, 0.4773]])
tensor([[-0.6088, -0.5521]])
tensor([[ 0.4500, -1.5426]])
tensor([[ 0.7650, -0.7890]])
tensor([[-0.4953, -2.1339]])
tensor([[1.4078, 0.8994]])
tensor([[-1.3083, -3.4020]])
tensor([[ 1.1550, -0.2264]])
tensor([[-0.6293, -0.8761]])
tensor([[ 1.3484, -0.3005]])
tensor([[ 1.1833, -0.9192]])
tensor([[ 0.2636, -0.2015]])
tensor([[-1.0070, -1.6989]])
tensor([[ 0.0565, -2.5766]])
tensor([[-0.8490, -0.2670]])
tensor([[-1.3845,  0.0892]])
tensor([[-0.1832,  1.9279]])
tensor([[0.0052, 1.6095]])
tensor([[-0.2936, -0.2316]])
tensor([[-1.5756, -1.3921]])
tensor([[ 0.2759, -0.4158]])
tensor([[-0.9376, -0.1340]])
tensor([[ 1.1186, -0.0326]])
tensor([[-1.0530,  1.1115]])
tensor([[ 0.1994, -0.535

tensor([[-2.6961, -1.6841]])
tensor([[-0.7514, -0.7597]])
tensor([[1.3039, 1.7468]])
tensor([[-0.8849,  0.5797]])
tensor([[0.5943, 0.6975]])
tensor([[ 0.3700, -0.2343]])
tensor([[-1.7326, -0.8353]])
tensor([[-0.3367,  0.7025]])
tensor([[-0.3299,  0.8569]])
tensor([[-1.1768,  0.6660]])
tensor([[0.5770, 0.4176]])
tensor([[ 0.2660, -0.8876]])
tensor([[0.9311, 0.4388]])
tensor([[-1.8503, -0.7036]])
tensor([[0.4894, 0.5593]])
tensor([[-0.0833, -0.4376]])
tensor([[-0.6567,  0.4884]])
tensor([[ 0.5994, -0.5937]])
tensor([[ 1.3852, -1.0087]])
tensor([[ 1.0290, -0.2070]])
tensor([[2.0046, 1.4540]])
tensor([[-0.3989,  0.2554]])
tensor([[-0.2495, -0.4089]])
tensor([[ 0.8915, -0.5310]])
tensor([[0.0941, 0.4582]])
tensor([[-2.6912,  1.8474]])
tensor([[-0.4500,  0.0921]])
tensor([[ 1.7142, -0.3642]])
tensor([[ 0.8878, -0.8931]])
tensor([[-1.8621,  0.2986]])
tensor([[-0.0404,  0.2298]])
tensor([[ 1.1506, -0.2605]])
tensor([[0.5572, 0.8464]])
tensor([[2.9633, 0.3514]])
tensor([[-0.0391, -0.2917]])
ten

tensor([[-0.4208, -0.1854]])
tensor([[2.2455, 1.3091]])
tensor([[-0.8357, -1.0517]])
tensor([[-1.1180,  0.2331]])
tensor([[-0.0741,  0.1530]])
tensor([[ 1.4222, -2.0768]])
tensor([[0.9375, 1.2319]])
tensor([[ 0.1277, -0.7221]])
tensor([[ 0.7122, -0.2613]])
tensor([[-1.0711,  1.7806]])
tensor([[-1.4484,  0.3689]])
tensor([[1.2736, 0.2322]])
tensor([[-0.1969, -0.0326]])
tensor([[-0.1097,  1.4229]])
tensor([[ 0.8716, -1.4400]])
tensor([[ 1.5840, -0.4013]])
tensor([[-1.5042, -0.7388]])
tensor([[1.5306, 0.4871]])
tensor([[-0.4224, -0.2413]])
tensor([[-0.9772,  0.5304]])
tensor([[-0.6472,  0.8016]])
tensor([[-1.8089,  0.6241]])
tensor([[ 1.0229, -1.9284]])
tensor([[0.1182, 1.3049]])
tensor([[ 0.7884, -0.6155]])
tensor([[-0.1289,  1.4816]])
tensor([[0.0313, 0.6435]])
tensor([[-0.7439, -0.4849]])
tensor([[ 0.7149, -0.3436]])
tensor([[ 0.6507, -0.3463]])
tensor([[-1.0360, -0.0491]])
tensor([[-1.0486,  1.4660]])
tensor([[-0.5307, -0.0792]])
tensor([[-0.9116, -0.6952]])
tensor([[-1.1643, -0.0216]

tensor([[0.9666, 0.6842]])
tensor([[-0.8799,  0.2810]])
tensor([[ 0.4863, -0.6234]])
tensor([[-0.2130,  0.0284]])
tensor([[0.5745, 1.4735]])
tensor([[2.3489, 2.7172]])
tensor([[ 1.6742, -1.0306]])
tensor([[-0.2890,  1.0234]])
tensor([[ 1.2087, -1.8274]])
tensor([[-0.0883, -1.5311]])
tensor([[ 1.7583, -1.4229]])
tensor([[-0.9381, -0.4667]])
tensor([[0.5179, 0.4928]])
tensor([[-2.0213, -1.2774]])
tensor([[ 0.0747, -0.4365]])
tensor([[-1.3112,  1.4934]])
tensor([[2.2558, 0.1210]])
tensor([[ 0.0232, -0.7531]])
tensor([[ 1.0876, -0.3068]])
tensor([[-0.6126, -0.6139]])
tensor([[-1.5670,  0.1092]])
tensor([[0.0316, 1.1376]])
tensor([[1.2676, 0.6391]])
tensor([[0.0120, 0.4064]])
tensor([[-1.1594,  1.2184]])
tensor([[-2.0369,  0.5465]])
tensor([[-0.5657,  0.2838]])
tensor([[1.6772, 0.8082]])
tensor([[ 0.5195, -1.1355]])
tensor([[ 1.9084, -0.8365]])
tensor([[-1.0374, -0.1902]])
tensor([[0.0679, 1.4690]])
tensor([[ 0.4095, -0.2746]])
tensor([[2.2765, 0.8969]])
tensor([[ 0.2711, -0.4515]])
tensor(

tensor([[0.8824, 0.4964]])
tensor([[-0.1161,  1.8228]])
tensor([[ 0.4025, -2.0659]])
tensor([[-0.0134, -2.7236]])
tensor([[-0.1273, -0.3401]])
tensor([[ 0.9974, -0.0517]])
tensor([[-0.3142,  2.5237]])
tensor([[0.2777, 0.7603]])
tensor([[-0.1670, -0.8290]])
tensor([[1.0112, 1.0513]])
tensor([[ 0.8220, -1.5902]])
tensor([[0.1081, 0.5865]])
tensor([[0.3079, 0.5839]])
tensor([[ 0.1539, -0.0060]])
tensor([[-1.5105,  0.2094]])
tensor([[0.0416, 1.0554]])
tensor([[-0.5728, -1.1012]])
tensor([[-1.1503, -1.1550]])
tensor([[-0.0193, -0.2982]])
tensor([[1.0618, 1.1802]])
tensor([[ 0.0892, -0.3225]])
tensor([[ 1.5659, -0.6531]])
tensor([[ 0.8079, -0.9576]])
tensor([[0.4210, 1.3835]])
tensor([[-0.0435, -2.3711]])
tensor([[1.0578, 0.2865]])
tensor([[-0.2717,  0.9596]])
tensor([[-0.1287, -0.6986]])
tensor([[ 1.4705, -0.4906]])
tensor([[ 0.8942, -2.1266]])
tensor([[-1.2213,  0.3956]])
tensor([[ 0.3576, -0.1361]])
tensor([[-1.4158,  0.2912]])
tensor([[1.5724, 0.1605]])
tensor([[-0.4401, -0.3915]])
tenso